### PR TITLE
Update commands.csv to add GCC High commands.

### PR DESCRIPTION
**Pull request by cjvandyk**
Update commands.csv to add GCC High commands.

### CODE REVIEW

**Comment by merill** [comment]
Thanks for the PR and sorry it took so long. 

Given it's just the domain that is switching, I'm thinking we could build an automation that generates the gcc links (instead of having to maintain it manually each time).

**Comment by tktackett** [comment]
When will this pull request be accepted? Automation would be excellent, but the lack of GCC High information prevents certain users from using the site.

**Comment by merill** [comment]
@cjvandyk  tx for the PR. I changed the urls to suffix. 
@tktackett tx for the reminder.

So I've made it **g** and **gh** as suffix (e.g. az**g**.cmd.ms).

My plan is in the future to make it az**.g.**cmd.ms so we can add more clouds as they come but keep the initial prefix the same.

**Comment by merill** [comment]
Please test and let me know if you see any issues.

BTW I used the **g** prefix by default for everything and only used **gh** when we **g** was already taken.

Do you think that makes sense or should we make all the GCC High as **gh** ?

Happy to change.

**Pull request merged**
